# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-xineramaproto
Summary:    X.Org X11 Protocol xineramaproto
Version:    1.2.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/xineramaproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-xineramaproto.yaml
Provides:   xineramaproto


%description
Xinerama is an X extension that allows clients to query information
about multiple physical screens controlled by a single X server that
appear as a single screen to core X11 protocol operations.




%prep
%setup -q -n xineramaproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/xineramaproto.pc
%{_includedir}/X11/extensions/panoramiXproto.h
# << files


